import { MILLI_PER_TILE, type Rect } from '@factor/sim';
import { expect, test } from 'vitest';
import { ARENA, towerFootprint } from '../src/index.ts';

// Side 1 (lowercase) at the top, side 0 (uppercase) at the bottom, as side 0's player sees it.
// K/k: Keep. O/o: Outpost. ~: river. =: bridge.
const MAP = `
..................
.......kkkk.......
.......kkkk.......
.......kkkk.......
.......kkkk.......
..ooo........ooo..
..ooo........ooo..
..ooo........ooo..
..................
..................
..................
..................
..................
..................
..................
~~===~~~~~~~~===~~
~~===~~~~~~~~===~~
..................
..................
..................
..................
..................
..................
..................
..OOO........OOO..
..OOO........OOO..
..OOO........OOO..
.......KKKK.......
.......KKKK.......
.......KKKK.......
.......KKKK.......
..................
`.trim();

function contains(rect: Rect, x: number, y: number): boolean {
  return x >= rect.x && x < rect.x + rect.width && y >= rect.y && y < rect.y + rect.height;
}

/** One character per tile, judged at the tile's center. */
function draw(): string {
  const half = MILLI_PER_TILE / 2;
  const rows: string[] = [];
  for (let row = ARENA.height / MILLI_PER_TILE - 1; row >= 0; row--) {
    let line = '';
    for (let col = 0; col < ARENA.width / MILLI_PER_TILE; col++) {
      const x = col * MILLI_PER_TILE + half;
      const y = row * MILLI_PER_TILE + half;
      const tower = ARENA.towers.find((site) => contains(towerFootprint(site), x, y));
      if (tower !== undefined) {
        const mark = tower.kind === 'keep' ? 'K' : 'O';
        line += tower.side === 0 ? mark : mark.toLowerCase();
      } else if (ARENA.bridges.some((bridge) => contains(bridge, x, y))) {
        line += '=';
      } else if (contains(ARENA.river, x, y)) {
        line += '~';
      } else {
        line += '.';
      }
    }
    rows.push(line);
  }
  return rows.join('\n');
}

test('the arena is 18 × 32 tiles and matches the map', () => {
  expect(ARENA.width).toBe(18 * MILLI_PER_TILE);
  expect(ARENA.height).toBe(32 * MILLI_PER_TILE);
  expect(draw()).toBe(MAP);
});
